export const homeTypes = {
  SET_ALL_PRODUCT: "SET_ALL_PRODUCT",
  SET_DETAIL_PRODUCT: "SET_DETAIL_PRODUCT",
  SET_HOBBY: "SET_HOBBY",
  SET_DATA_SEARCH: "SET_DATA_SEARCH",
};

export const productTypes = {
  SET_PRODUCT_DETAIL: "SET_PRODUCT_DETAIL",
};
export const sortTypes = {
  SORT_DAY_INCREASED: "SORT_DAY_INCREASED",
  SORT_DAY_DECREASED: "SORT_DAY_DECREASED",
  SORT_VIEWS_INCREASED: "SORT_VIEWS_INCREASED",
  SORT_VIEWS_DECREASED: "SORT_VIEWS_DECREASED",
  SORT_SALES_INCREASED: "SORT_SALES_INCREASED",
  SORT_SALES_DECREASED: "SORT_SALES_DECREASED",
  SORT_PRICE_INCREASED: "SORT_PRICE_INCREASED",
  SORT_PRICE_DECREASED: "SORT_PRICE_DECREASED",
};

export const cartTypes = {
  ADD_CART: "ADD_CART",
  SET_CART: "SET_CART",
  SET_CITY: "SET_CITY",
  SET_DICTRICT: "SET_DISTRICT",
  SET_WARD: "SET_WARD",
  PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
  PAYMENT_FAIL: "PAYMENT_FAIL",
  RESET_PAYMENT: "RESET_PAYMENT",
};
export const purchaseHistoryTypes = {
  SET_PURCHASED_HISTORY: "SET_PURCHASED_HISTORY",
};
